### ISSUE TITLE
__container: unbound variable

### ISSUE THREAD

**Issue by lvnilesh** [Protektor-Desura/jellyfin-dvr-comskip#1]
```
[post-process.sh] Transcoding file..
./jellyfin-drv-comskip.sh: line 81: __container: unbound variable
```

**Comment by lvnilesh** [comment]
This issue seems to have been closed prematurely. 

The pull request https://github.com/Protektor-Desura/jellyfin-dvr-comskip/pull/2 related to this issue is still open and unmerged.

**Comment by famewolf** [comment]
The container is defined with three underscores but when called from the ffmpeg line only two underscores are used.  Add the additional one to fix this.  I used perplexity to fix several issues with the script as well as adding hardware encoding/decoding for intel quicksync.   The major issue though is that COMSKIP executable which both comcut and comchap call isn't included in the folder.   I question how anyone could get this to work asis.
